# Numpy Overview

**This tutorial gives a quick overview of the numpy arrays and its features**<br>
> - **Importing numpy library**<br>
> - **Creating arrays and initializing**<br>
> - **Reading arrays from files**<br>
> - **Special initializing functions**<br>
> - **Slicing and indexing**<br>
> - **reshaping arrays**<br>
> - **Numpy Maths**<br>
> - **Combining arrays**<br>
> - **Basic algebraic operations using numpy arrays**<br>
> - **Solving linear equations**<br>
> - **Matix inversions**<br>
> - **Calculating eigen vectors**<br>

# Importing numpy library

In [ ]:
from numpy import * 

In [1]:
import numpy as np

In [4]:
print dir(np),

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__config__', '__doc__', '__file__', '__git_revision__', '__mkl_version__', '__name__', '__package__', '__path__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', 'abs', 'absolute', 'absolute_import', 'add', 'add_docstring', 'add_newdoc', 'add_newdoc

In [10]:
np.ndarray(range(1,10), dtype='float')

array([[[[[[[[[ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              ..., 
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

             [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              ..., 
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

             [[ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              ..., 
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.],
              [ 0.,  0.,  0., ...,  0.,  0.,  0.]],

             ...

# Creating one dimensional numpy arrays and initializing

In [11]:
arr_1 = np.array([[1,2,4], [2,3,4], [1,2,10]], dtype='int64')
print arr_1

[[ 1  2  4]
 [ 2  3  4]
 [ 1  2 10]]


In [17]:
arr_1[2,2]

10

In [13]:
arr_1[2,:]

array([ 1,  2, 10], dtype=int64)

In [14]:
arr_1[:,0]

array([1, 2, 1], dtype=int64)

In [16]:
arr_1[1,1:3]

array([3, 4], dtype=int64)

In [12]:
print arr_1[2,0:2]

[1 2]


In [125]:
range(1,10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [118]:
arr_1.dtype

dtype('int64')

In [18]:
type(arr_1)

numpy.ndarray

In [19]:
arr_1.T

array([[ 1,  2,  1],
       [ 2,  3,  2],
       [ 4,  4, 10]], dtype=int64)

In [21]:
arr_1.shape

(3L, 3L)

In [22]:
arr_1.size

9

In [24]:
arr_1.trace()

14

In [26]:
arr_1.sum()

29

In [25]:
arr_1.mean()

3.2222222222222223

In [27]:
arr_1.nbytes

72

In [29]:
arr_1.sort()
arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]], dtype=int64)

In [106]:
print dir(arr_1),

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_wrap__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__delslice__', '__div__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getslice__', '__gt__', '__hash__', '__hex__', '__iadd__', '__iand__', '__idiv__', '__ifloordiv__', '__ilshift__', '__imod__', '__imul__', '__index__', '__init__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__oct__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdiv__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__

In [32]:
arr_1.ndim

2

In [33]:
a1 = np.array([1,2,20,10])

In [34]:
a1.ndim

1

In [110]:
arr_1.std()

2.6152449546532934

In [114]:
arr_1.dtype

dtype('int32')

In [4]:
## Create one dimensional array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [5]:
## Find the typbe of the object
type(a)

numpy.ndarray

# Numpy Arrays - dtypes & shapes

In [6]:
## Find the dimension of the array
a.shape

(3L,)

In [7]:
a.dtype

dtype('int32')

In [8]:
print( a[1] )

2


# Creating two dimensional numpy arrays and initializing

In [10]:
# Create a two dimensional array
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print( b )

[[1 2 3]
 [4 5 6]]


In [11]:
print( b.shape )

(2L, 3L)


In [12]:
print( b[0, :] )

[1 2 3]


In [13]:
print( b[:, 1] )

[2 5]


In [14]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

# Reading an array from a file

### narray.txt
>2,4,6,7 <br>
>1,2,3,5 <br>
>3,2,7,8 <br>
>1,5,6,4 <br>

In [35]:
f = np.loadtxt("C:\\Users\\ChandraMouli\\Desktop\\narray.txt", delimiter=',')

In [133]:
np.load?

In [36]:
f

array([[ 2.,  4.,  6.,  7.],
       [ 1.,  2.,  3.,  5.],
       [ 3.,  2.,  7.,  8.],
       [ 1.,  5.,  6.,  4.]])

In [37]:
f = np.loadtxt("C:\\Users\\ChandraMouli\\Desktop\\narray.txt", delimiter=',', dtype = "int")

In [38]:
f

array([[2, 4, 6, 7],
       [1, 2, 3, 5],
       [3, 2, 7, 8],
       [1, 5, 6, 4]])

In [39]:
f.dtype

dtype('int32')

# Special Initializing functions

>zeros, ones, eye, full, random, diag

In [134]:
a = np.zeros((3,3))  # Create an array of all zeros
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [135]:
b = np.ones((5,2)) # Create an array of all ones
b

array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [136]:
d = np.eye(3)
d

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
d

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [137]:
c = np.full((2,2), 7)

In [138]:
c

array([[ 7.,  7.],
       [ 7.,  7.]])

In [39]:
e = np.random.random((2,2) )

In [40]:
e

array([[ 0.07034518,  0.59617226],
       [ 0.77988305,  0.71271132]])

In [41]:
f = np.random.randint(100, size = (4,4) )

In [42]:
f

array([[46, 94, 36, 58],
       [40, 83, 39, 69],
       [62, 54, 31, 24],
       [29,  7,  5, 31]])

# Slicing & Indexing an array 

In [43]:
# Get first row
f[0,:]

array([46, 94, 36, 58])

In [44]:
# Get 1 and 2 row
f[0:2,:]

array([[46, 94, 36, 58],
       [40, 83, 39, 69]])

In [45]:
f[:, 1]

array([94, 83, 54,  7])

In [46]:
# Get first column
f[:,0]

array([46, 40, 62, 29])

In [47]:
f[:,0:2]

array([[46, 94],
       [40, 83],
       [62, 54],
       [29,  7]])

In [48]:
## slicing an array 
## All 
b = f[:2, 1:3]

In [49]:
b

array([[94, 36],
       [83, 39]])

In [50]:
## Get specific elements
np.array([f[0,1], f[2,2]])

array([94, 31])

In [43]:
arr_1>=3

array([[False, False,  True],
       [False,  True,  True],
       [False, False,  True]], dtype=bool)

In [42]:
arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]], dtype=int64)

In [44]:
arr_1[arr_1>=3]

array([ 4,  3,  4, 10], dtype=int64)

In [56]:
## Boolean indexing
f>80

array([[False,  True, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]], dtype=bool)

In [150]:
arr_2 = np.array([range(0,10), range(10,20), range(20,30)])
arr_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [152]:
arr_2[arr_2>20]

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [153]:
arr_2.shape

(3L, 10L)

In [155]:
d=np.reshape(arr_2, (5,6))

In [156]:
d[4,:]=0

In [157]:
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [ 0,  0,  0,  0,  0,  0]])

In [57]:
g = f[f>80]

In [58]:
g

array([94, 83])

# Reshaping an array

In [59]:
k = np.reshape( f, ( 8,2 ) )

In [45]:
arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]], dtype=int64)

In [47]:
np.reshape(arr_1, (1,9))

array([[ 1,  2,  4,  2,  3,  4,  1,  2, 10]], dtype=int64)

In [60]:
k

array([[46, 94],
       [36, 58],
       [40, 83],
       [39, 69],
       [62, 54],
       [31, 24],
       [29,  7],
       [ 5, 31]])

# Updating an array

In [48]:
arr_1

array([[ 1,  2,  4],
       [ 2,  3,  4],
       [ 1,  2, 10]], dtype=int64)

In [49]:
arr_1[arr_1>=3]=10

In [50]:
arr_1

array([[ 1,  2, 10],
       [ 2, 10, 10],
       [ 1,  2, 10]], dtype=int64)

In [61]:
k[7,1] = 0

In [62]:
k

array([[46, 94],
       [36, 58],
       [40, 83],
       [39, 69],
       [62, 54],
       [31, 24],
       [29,  7],
       [ 5,  0]])

In [63]:
k[5:] = 0

In [64]:
k

array([[46, 94],
       [36, 58],
       [40, 83],
       [39, 69],
       [62, 54],
       [ 0,  0],
       [ 0,  0],
       [ 0,  0]])

# NUMPY Maths
## Adding, subtracting, multiplying, transposing arryas

In [51]:
x = np.random.randint( 100, size = (5,5) )
y = np.random.randint( 100, size = (5,5) )

In [52]:
x

array([[ 2, 62, 73, 51, 98],
       [10, 33, 73, 45, 87],
       [85, 74, 49, 60, 43],
       [54, 13, 78, 14, 62],
       [71, 70, 81, 38, 42]])

In [53]:
y

array([[32, 13, 13, 30, 50],
       [12, 91, 63, 84, 71],
       [85, 91, 84, 73, 88],
       [23, 67, 23, 25, 53],
       [58,  3, 16, 53, 22]])

In [54]:
## Add two matrices x + y or np.add( x, y )
x + y

array([[ 34,  75,  86,  81, 148],
       [ 22, 124, 136, 129, 158],
       [170, 165, 133, 133, 131],
       [ 77,  80, 101,  39, 115],
       [129,  73,  97,  91,  64]])

In [56]:
np.add( x, y )

array([[ 34,  75,  86,  81, 148],
       [ 22, 124, 136, 129, 158],
       [170, 165, 133, 133, 131],
       [ 77,  80, 101,  39, 115],
       [129,  73,  97,  91,  64]])

In [57]:
# np.substract( x, y )
x - y

array([[-30,  49,  60,  21,  48],
       [ -2, -58,  10, -39,  16],
       [  0, -17, -35, -13, -45],
       [ 31, -54,  55, -11,   9],
       [ 13,  67,  65, -15,  20]])

In [58]:
# np.multiply( x, y )
x * y

array([[  64,  806,  949, 1530, 4900],
       [ 120, 3003, 4599, 3780, 6177],
       [7225, 6734, 4116, 4380, 3784],
       [1242,  871, 1794,  350, 3286],
       [4118,  210, 1296, 2014,  924]])

In [59]:
# Matrix Transpose
x.T

array([[ 2, 10, 85, 54, 71],
       [62, 33, 74, 13, 70],
       [73, 73, 49, 78, 81],
       [51, 45, 60, 14, 38],
       [98, 87, 43, 62, 42]])

# Calculating column sums and row sums

In [60]:
x = np.random.randint( 10, size = (4,4) )

In [61]:
x

array([[2, 9, 6, 4],
       [6, 5, 5, 5],
       [3, 6, 0, 4],
       [6, 1, 4, 1]])

In [62]:
print x.sum(), x.mean(), x.std()

67 4.1875 2.26987747467


In [66]:
np.sum(x, axis=0)

array([17, 21, 15, 14])

In [67]:
x+[10,15,20,30]

array([[12, 24, 26, 34],
       [16, 20, 25, 35],
       [13, 21, 20, 34],
       [16, 16, 24, 31]])

In [176]:
l=np.array([[10,20], [20,30]])

In [177]:
l+10

array([[20, 30],
       [30, 40]])

In [178]:
x

array([[1, 4, 5, 4],
       [5, 7, 5, 4],
       [7, 8, 7, 8],
       [9, 7, 0, 4]])

In [179]:
np.std(x)

2.4165768661476505

In [77]:
np.sum( x, axis = 0 )

array([20, 22, 15, 23])

In [78]:
np.sum( x, axis = 1 )

array([22, 22, 21, 15])

In [79]:
np.mean( x, axis = 0 )

array([ 5.  ,  5.5 ,  3.75,  5.75])

In [80]:
np.mean( x, axis = 1 )

array([ 5.5 ,  5.5 ,  5.25,  3.75])

# Combine Arrays 

In [68]:
x = np.random.randint( 10, size = (2,2) )
y = np.random.randint( 100, size = (2,2) )

In [69]:
x

array([[2, 2],
       [6, 6]])

In [70]:
y

array([[ 4, 37],
       [20, 67]])

In [71]:
np.vstack( [x, y])

array([[ 2,  2],
       [ 6,  6],
       [ 4, 37],
       [20, 67]])

In [72]:
np.hstack([x, y])

array([[ 2,  2,  4, 37],
       [ 6,  6, 20, 67]])

# Linear Algebra.. Advanced Matrix Operation

In [87]:
from numpy import linalg
import numpy as np

# Solving a set of linear equations 
> 2x + 2y+3z = 5 <br>
> 3x + y +4z = 7 <br>
> 4x + 3y =10

In [82]:
a = np.array([[2,2,3], [3,1,4],[4,3,0]])
b = np.array([5,7,10])
x = np.linalg.solve(a, b)
x

array([ 2.30434783,  0.26086957, -0.04347826])

# Matrix Inversion

In [75]:
a = np.array([[1, 2], [3, 4]])
np.linalg.inv( a )

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# Calculating an eigen value and vector for a matrix

In [76]:
m1 = np.diag((1, 2, 3))
m1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [78]:
eigval, eigvec = np.linalg.eig( m1 )

In [79]:
eigval

array([ 1.,  2.,  3.])

In [80]:
eigvec

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])